{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/admin-side.phtml" /}
    {include file="../application/index/view/public/admin-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>商品管理</h3>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>商品名称</th>
                        <th>原价格</th>
                        <th>意向商品</th>
                        <th>描述</th>
                        <th>商品状态</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if(!empty($pager['data'])):?>
                        <?php foreach ($pager['data'] as $key=>$data):?>
                          <tr role="row">
                            <td><?php echo $data['name'];?></td>
                            <td><?php echo $data['price'];?></td>
                            <td><?php echo $data['want_to_goods'];?></td>
                            <td><?php echo $data['describe'];?></td>
                            <td>
                              <?php if($data['status'] == 0):?>
                                <?php echo '待发布' ;?>
                              <?php elseif($data['status'] == 1):?>
                                <?php echo '发布中' ;?>
                              <?php else:?>
                                <?php echo '已匹配' ;?>
                              <?php endif;?>
                            </td>
                            <td>
                              <a class="btn btn-info btn-sm look" href="<?php echo $data['photo'];?>" target="_blank">查看图片</a>
                              <button class="btn btn-danger btn-sm downGood" data-id="<?php echo $data['id'];?>">商品下架</button>
                            </td>
                          </tr>
                        <?php endforeach;?>
                      <?php else:?>
                        <td colspan="8" style="text-align: center;">暂无信息</td>
                      <?php endif;?>
                    </tbody>
                  </table>
                  <?php if(!empty($pager['data'])):?>
                    {include file="../application/index/view/public/pager.phtml" /}
                  <?php endif;?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
      (() => {
        // 商品下架
        $('.downGood').click(function() {
          if (confirm('确定下架该商品吗？')) {
            const params = {
              id: $(this).attr('data-id')
            }
            $.post('/admin/manage/downgoods', params, (res) => {
              if (res.status === true) {
                location.reload();
              } else {
                alert(res.msg);
              }
            })
          }
        });
      })();
    </script>
{include file="../application/index/view/public/footer.phtml" /}