{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/admin-side.phtml" /}
    {include file="../application/index/view/public/admin-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>举报管理</h3>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>订单号</th>
                        <th>举报人</th>
                        <th>被举报人</th>
                        <th>举报类型</th>
                        <th>原因</th>
                        <th>状态</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if(!empty($pager['data'])):?>
                        <?php foreach ($pager['data'] as $key=>$data):?>
                          <tr role="row">
                            <td><?php echo $data['order_id'];?></td>
                            <td><?php echo $data['user_id'];?></td>
                            <td><?php echo $data['report_user_id'];?></td>
                            <td>
                              <?php if($data['type'] == 0):?>
                                <?php echo '普通' ;?>
                              <?php elseif($data['type'] == 1):?>
                                <?php echo '交易举报' ;?>
                              <?php else:?>
                                <?php echo '信誉举报' ;?>
                              <?php endif;?> 
                            </td>
                            <td><?php echo $data['reason'];?></td>
                            <td><?php echo $data['is_deal'] == 0 ? '待处理' : '已处理';?></td>
                            <td>
                              <?php if($data['is_deal'] == 0):?>
                                <button class="btn btn-info btn-sm handle" data-id="<?php echo $data['id'];?>">处理</button>
                                <button class="btn btn-info btn-sm handle_del" data-id="<?php echo $data['id'];?>">删除</button>
                              <?php endif;?>
                            </td>
                          </tr>
                        <?php endforeach;?>
                      <?php else:?>
                        <td colspan="5" style="text-align: center;">暂无信息</td>
                      <?php endif;?>
                    </tbody>
                  </table>
                  <?php if(!empty($pager['data'])):?>
                    {include file="../application/index/view/public/pager.phtml" /}
                  <?php endif;?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
      (() => {
        // 举报处理
        $('.handle').click(function() {
          if (confirm('确定处理该举报订单？')) {
            const params = {
              id: $(this).attr('data-id')
            }
            $.post('/admin/manage/dealreport', params, (res) => {
              if (res.status === true) {
                location.reload();
              } else {
                alert(res.msg);
              }
            })
          }
        });
        //删除处理
        $('.handle_del').click(function() {
          if (confirm('确定删除该举报订单？')) {
            const params = {
              id: $(this).attr('data-id'),
              del:1
            };
            $.post('/admin/manage/dealreport', params, (res) => {
              if (res.status === true) {
                location.reload();
              } else {
                alert(res.msg);
              }
            })
          }
        });
      })();
    </script>
{include file="../application/index/view/public/footer.phtml" /}