{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/admin-side.phtml" /}
    {include file="../application/index/view/public/admin-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>用户管理列表</h3>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>帐号</th>
                        <th>昵称</th>
                        <th>性别</th>
                        <th>所在学校</th>
                        <th>专业</th>
                        <th>信誉度</th>
                        <th>审核状态</th>
                        <th>冻结状态</th>
                        <th>注册时间</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if(!empty($pager['data'])):?>
                        <?php foreach ($pager['data'] as $key=>$data):?>
                          <tr role="row">
                            <td><?php echo $data['email'];?></td>
                            <td><?php echo $data['nick_name'];?></td>
                            <td><?php echo $data['sex'];?></td>
                            <td><?php echo $data['shoole'];?></td>
                            <td><?php echo $data['major'];?></td>
                            <td><?php echo $data['credit'];?></td>
                            <td><?php echo $data['is_effect'] == 0 ? '未审核' : '已审核';?></td>
                            <td><?php echo $data['isdel'] == 0 ? '正常' : '冻结';?></td>
                            <td><?php echo $data['create_time'];?></td>
                            <td>
                              <?php if ($data['is_effect'] == 0) :?>
                                <button class="btn btn-info btn-sm effect" data-id="<?php echo $data['id'];?>">审核</button>
                              <?php endif;?>
                              <?php if ($data['isdel'] == 0) :?>
                                <button class="btn btn-info btn-sm delete" data-id="<?php echo $data['id'];?>">冻结</button>
                              <?php endif;?>
                            </td>
                          </tr>
                        <?php endforeach;?>
                        <?php else:?>
                          <td colspan="10" style="text-align: center;">暂无信息</td>
                      <?php endif;?>
                    </tbody>
                  </table>
                  <?php if(!empty($pager['data'])):?>
                    {include file="../application/index/view/public/pager.phtml" /}
                  <?php endif;?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
      (() => {
        // 审核
        $('.effect').click(function() {
          if (confirm('确定审核通过该用户？')) {
            const params = {
              userId: $(this).attr('data-id')
            }
            $.post('/admin/manage/auidtuser', params, (res) => {
              if (res.status === true) {
                location.reload();
              } else {
                alert(res.msg);
              }
            })
          }
        });
        // 冻结
        $('.delete').click(function() {
          if (confirm('确定冻结该用户？')) {
            const params = {
              userId: $(this).attr('data-id')
            }
            $.post('/admin/manage/deluser', params, (res) => {
              if (res.status === true) {
                location.reload();
              } else {
                alert(res.msg);
              }
            })
          }
        });
      })();
    </script>
{include file="../application/index/view/public/footer.phtml" /}