<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>交易管理系统</title>
    <!-- Bootstrap -->
    <link href="/assets/plugins/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/assets/plugins/nprogress/nprogress.css" rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="/assets/plugins/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="/assets/css/build/custom.min.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="/assets/plugins/animate.css/animate.min.css" rel="stylesheet">
    <!-- jQuery -->
    <script src="/assets/plugins/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/assets/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
  </head>

  <body class="login">
    <div>
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form class="form-horizontal">
              <h1>登录</h1>
              <div>
                <input type="text" class="form-control" placeholder="用户名" id="userName">
              </div>
              <div>
                <input type="password" class="form-control" placeholder="密码" id="password">
              </div>
              <div style="margin-bottom: 10px;">
                <input type="text" class="form-control" placeholder="验证码" id="code" style="width: 226px;display: inline-block;vertical-align: middle;margin: 0;">
                <a style="vertical-align: middle;display: inline-block;height: 34px;margin: 0;"><img src="/index/captcha/?channel=userLogin"></a>
              </div>
              <div class="clearfix"></div>
              <div>
                <a class="btn btn-default" id="login">登录</a>
              </div>
              <div class="clearfix"></div>
              <div class="separator">
                <p class="change_link">没有帐号 ?
                  <a href="/user/regist" class="to_register">前往注册</a>
                </p>
                <div class="clearfix"></div>
                <br />
              </div>
            </form>
          </section>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      $(function(){
        // 登录
        $('#login').click(function() {
          var params = {
            userName: $('#userName').val(),
            password: $('#password').val(),
            code: $('#code').val(),
          }
          //登陆
          $.get('/user/login/i', params, function(data){
            if (data.status === true) {
              window.location.href = '/'
            } else {
              alert(data.msg)
            }
          })
        })

        document.onkeydown = function(e){    
          var e = window.event ? window.event:e;
          if(e.keyCode == 13){
            $('#login').click()
         }
        }
      })
    </script>
    <script src="/assets/plugins/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/assets/plugins/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="/assets/plugins/Chart.js/dist/Chart.min.js"></script>
    <!-- jQuery Sparklines -->
    <script src="/assets/plugins/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
    <!-- Flot -->
    <script src="/assets/plugins/Flot/jquery.flot.js"></script>
    <script src="/assets/plugins/Flot/jquery.flot.pie.js"></script>
    <script src="/assets/plugins/Flot/jquery.flot.time.js"></script>
    <script src="/assets/plugins/Flot/jquery.flot.stack.js"></script>
    <script src="/assets/plugins/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="/assets/plugins/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="/assets/plugins/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="/assets/plugins/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="/assets/plugins/DateJS/build/date.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="/assets/plugins/moment/min/moment.min.js"></script>
    <script src="/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
    
    <!-- Custom Theme Scripts -->
    <script src="/assets/plugins/build/custom.min.js"></script>
  </body>
</html>