{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/user-side.phtml" /}
    {include file="../application/index/view/public/nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>首页</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{include file="../application/index/view/public/footer.phtml" /}