{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/user-side.phtml" /}
    {include file="../application/index/view/public/user-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>商品管理</h3>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-10 col-md-10">
                  <button class="btn btn-primary btn-sm" id="showAddGoodModal">添加商品</button>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>商品Id</th>
                        <th>商品名称</th>
                        <th>原价格</th>
                        <th>意向商品</th>
                        <th>描述</th>
                        <th>商品状态</th>
                        <th>置换请求数量</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if(!empty($pager['data'])):?>
                        <?php foreach ($pager['data'] as $key=>$data):?>
                          <tr role="row">
                            <td><?php echo $data['id'];?></td>
                            <td><?php echo $data['name'];?></td>
                            <td><?php echo $data['price'];?></td>
                            <td><?php echo $data['want_to_goods'];?></td>
                            <td><?php echo $data['describe'];?></td>
                            <td>
                              <?php if($data['status'] == 0):?>
                                <?php echo '待发布' ;?>
                              <?php elseif($data['status'] == 1):?>
                                <?php echo '发布中' ;?>
                              <?php else:?>
                                <?php echo '已匹配' ;?>
                              <?php endif;?>
                            </td>
                            <td><?php echo $data['requestNum'];?></td>
                            <td>
                              <a class="btn btn-info btn-sm look" href="<?php echo $data['photo'];?>" target="_blank">查看图片</a>
                              <a class="btn btn-info btn-sm look" href="/user/order/goodsdetail?id=<?php echo $data['id'];?>" target="_blank">置换请求列表</a>
                              <button class="btn btn-info btn-sm edit" data-info="<?php echo implode(',', $data);?>">修改</button>
                            </td>
                          </tr>
                        <?php endforeach;?>
                      <?php else:?>
                        <td colspan="8" style="text-align: center;">暂无信息</td>
                      <?php endif;?>
                    </tbody>
                  </table>
                  <?php if(!empty($pager['data'])):?>
                    {include file="../application/index/view/public/pager.phtml" /}
                  <?php endif;?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade bs-example-modal-md" id="addGoodModal">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">添加商品</h4>
          </div>
          <div class="modal-body open-user-modal">
            <form class="form-horizontal form-label-left" id="addGoodForm">
              <div class="form-group">
                <label class="control-label col-sm-3" for="name">商品名称</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="name" type="text" class="form-control" placeholder="请输入商品名称">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="price">原价格</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="price" type="number" class="form-control" placeholder="请输入原价格">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="want_to_goods">意向商品</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="want_to_goods" type="text" class="form-control" placeholder="请输入意向商品">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="describe">详情描述</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <textarea name="describe" class="form-control" placeholder="详情描述"></textarea>
                </div>
              </div>
            </form>
            <form class="form-horizontal form-label-left" enctype="multipart/form-data" id="addUpdateImage">
              <div class="form-group">
                <label class="control-label col-sm-3" for="describe">图片</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input type="file" name="" id="addImageInput">
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="addGood">添加</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade bs-example-modal-md" id="editGoodModal">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">修改地址</h4>
          </div>
          <div class="modal-body open-user-modal">
            <form class="form-horizontal form-label-left" id="editGoodForm">
              <input id="id" type="hidden" name="id">
              <div class="form-group">
                <label class="control-label col-sm-3" for="name">商品名称</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="name" type="text" class="form-control" placeholder="请输入商品名称" id="name">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="price">原价格</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="price" type="number" class="form-control" placeholder="请输入原价格" id="price">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="want_to_goods">意向商品</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="want_to_goods" type="text" class="form-control" placeholder="请输入意向商品" id="want_to_goods">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="describe">详情描述</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <textarea name="describe" class="form-control" placeholder="详情描述" id="describe"></textarea>
                </div>
              </div>
            </form>
            <form class="form-horizontal form-label-left" enctype="multipart/form-data" id="addUpdateImage">
              <div class="form-group">
                <label class="control-label col-sm-3" for="describe">图片</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input type="file" name="" id="editImageInput">
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="editGood">修改</button>
          </div>
        </div>
      </div>
    </div>

    <script>
      (() => {
        // 添加商品
        let addGoodData = {};
        let editGoodData = {};
        $('#showAddGoodModal').click(() => {
          $('#addGoodModal').modal('show');
        });
        // 图片上传
        $('#addImageInput').change(function() {
          let formData = new FormData();
          formData.append("upload_img",$("#addImageInput")[0].files[0]);
          $.ajax({
            url: "/user/goods/imgupload",
            type: "post",
            data: formData,
            async: true,
            cache: false,
            contentType: false,
            processData: false,
            success: function(res){
              alert(res.msg);
              if (res.code === true) {
                addGoodData.photo = res.data.fileName;
              }
            },
            error: function(res){
              alert(res.msg);
            }
          });
        });
        $('#addGood').click(() => {
          let params = {
            ...addGoodData,
          }
          const arr = $('#addGoodForm').serializeArray();
          for (let i = 0; i < arr.length; i++) {
            params[arr[i].name] = arr[i].value;
          }
          $.post('/user/goods/add', params, (res) => {
            if (res.status === true) {
              location.reload();
            } else {
              alert(res.msg);
            }
          })
        });
        // 修改地址
        $('.edit').click(function() {
          const arr = $(this).attr('data-info').split(',');
          $('#id').val(arr[0]);
          $('#name').val(arr[1]);
          $('#price').val(arr[2]);
          $('#describe').val(arr[3]);
          $('#want_to_goods').val(arr[5]);
          $('#editGoodModal').modal('show');
        });
        // 图片上传
        $('#editImageInput').change(function() {
          let formData = new FormData();
          formData.append("upload_img",$("#editImageInput")[0].files[0]);
          $.ajax({
            url: "/user/goods/imgupload",
            type: "post",
            data: formData,
            async: true,
            cache: false,
            contentType: false,
            processData: false,
            success: function(res){
              alert(res.msg);
              if (res.code === true) {
                editGoodData.photo = res.data.fileName;
              }
            },
            error: function(res){
              alert(res.msg);
            }
          });
        });
        $('#editGood').click(() => {
          let params = {
            ...editGoodData,
          }
          const arr = $('#editGoodForm').serializeArray();
          for (let i = 0; i < arr.length; i++) {
            params[arr[i].name] = arr[i].value;
          }
          $.post('/user/goods/update', params, (res) => {
            if (res.status === true) {
              location.reload();
            } else {
              alert(res.msg);
            }
          })
        });
      })();
    </script>
{include file="../application/index/view/public/footer.phtml" /}