{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/user-side.phtml" /}
    {include file="../application/index/view/public/user-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
          <p style="height: 30px;line-height: 30px;margin: 0;">系统公告：<span id="msg"></span></p>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="flex center">
                <?php if(!empty($pager['data'])):?>
                  <?php foreach ($pager['data'] as $key=>$data):?>
                    <div class="flex-2 shadow" style="position: relative;">
                      <div class="img-wrapper flex center">
                        <img src="<?php echo $data['photo'];?>" alt="图片丢失">
                      </div>
                      <p style="margin: 0;color: #666;;"><span>商品发布人：</span><?php echo $data['userName'];?><span style="padding: 0 0 0 20px;">商品名称：</span><?php echo $data['name'];?></p>
                      <p style="margin: 0;margin-top: 2px;color: #666;"><span>商品原价格：</span><?php echo $data['price'];?><span style="padding: 0 0 0 20px;">意向物品：</span><?php echo $data['want_to_goods'];?></p>
                      <div style="margin: 0;margin-top: 2px;color: #666;">
                        <button class="btn btn-info btn-sm view" data-desc="<?php echo $data['describe'];?>">查看详情</button>
                        <button class="btn btn-info btn-sm add" data-id="<?php echo $data['id'];?>" data-name="<?php echo $data['name'];?>">发起置换请求</button>
                      </div>
                    </div>
                  <?php endforeach;?>
                <?php endif;?>
              </div>
              <?php if(!empty($pager['data'])):?>
                {include file="../application/index/view/public/pager.phtml" /}
              <?php endif;?>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade bs-example-modal-md" id="showModal">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">商品详情</h4>
          </div>
          <div class="modal-body open-user-modal">
            <p id="desc"></p>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade bs-example-modal-md" id="addRequestModal">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">发起置换请求</h4>
          </div>
          <div class="modal-body open-user-modal">
            <form class="form-horizontal form-label-left" id="addRequestForm">
              <input name="goodsId" type="hidden" id="goodsId">
              <div class="form-group">
                <label class="control-label col-sm-3" for="goodsName">意向商品</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="goodsName" type="text" class="form-control" disabled id="goodsName">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="changeId">置换商品Id</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="changeId" type="text" class="form-control" placeholder="请输入置换商品Id">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="changeName">置换商品商品</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="changeName" type="text" class="form-control" id="changeName">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="changeDescribe">置换商品详情描述</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <textarea name="changeDescribe" class="form-control" placeholder="详情描述" id="changeDescribe"></textarea>
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="addRequest">确定发起</button>
          </div>
        </div>
      </div>
    </div>

    <script>
      (() => {
        // 获取系统公告信息
        $.post('/index/index/sysmsg', {}, (res) => {
          let len = res.data.length;
          let i = 0;
          $('#msg').html(res.data[i].content + '<span style="padding: 0 4px 0 20px;">--</span>' + res.data[i].create_at);
          setInterval(() => {
            i++;
            if (i === len) {
              i = 0;
            }
            $('#msg').html(res.data[i].content + '<span style="padding: 0 4px 0 20px;">--</span>' + res.data[i].create_at);
          }, 5000);
          console.log(res);
        });
        // 发起置换请求
        $('.add').click(function() {
            $.get('/index/index/is_login',function (returnJson) {
               if(returnJson.status == false){
                   window.location.href = "/user/login/index";
               }
            });
          $('#goodsId').val($(this).attr('data-id'));
          $('#goodsName').val($(this).attr('data-name'));
          $('#addRequestModal').modal('show');
        });
        $('#addRequest').click(() => {
          const params = $('#addRequestForm').serializeArray();
          $.post('/user/request/add', params, (res) =>{
            if (res.status === true) {
              window.location.href = "/user/request/index";
            } else {
              alert(res.msg);
            }
          })
        });
        // 查看详情
        $('.view').click(function() {
          $('#desc').html($(this).attr('data-desc'));
          $('#showModal').modal('show');
        });
      })();
    </script>
{include file="../application/index/view/public/footer.phtml" /}