{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/user-side.phtml" /}
    {include file="../application/index/view/public/user-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>订单详情</h3>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>置换用户（对方）</th>
                        <th>置换商品（对方）</th>
                        <th>我的置换商品</th>
                        <th>状态</th>
                        <th>我的反馈</th>
                        <th>反馈处理情况</th>
                        <th>对方反馈</th>
                        <th>对方反馈处理情况</th>
                      </tr>
                    </thead>
                    <tbody>
                        <tr role="row">
                            <td><?php echo empty($changer['nick_name'])?$changer['email']:$changer['nick_name'].'('.$changer['email'].')';?></td>
                            <td><?php echo $changeGoods;?></td>
                            <td><?php echo $myGoods;?></td>
                            <td><?php echo isset($orderStatus[$order['status']])?$orderStatus[$order['status']]:'';?></td>
                            <td><?php echo $order['my_report'];?></td>
                            <td><?php echo $order['my_report_status'];?></td>
                            <td><?php echo $order['reported'];?></td>
                            <td><?php echo $order['reported_status'];?></td>
                        </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
    </script>
{include file="../application/index/view/public/footer.phtml" /}