{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/user-side.phtml" /}
    {include file="../application/index/view/public/user-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>置换请求列表</h3>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-12">
                  <p>商品：<?php echo $goods['name'] ;?></p>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>待置换商品名称</th>
                        <th>待置换商品描述</th>
                        <th>待置换用户</th>
                        <th>状态</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if(!empty($request)):?>
                        <?php foreach ($request as $key=>$data):?>
                          <tr role="row">
                            <td><?php echo $data['change_goods_name'];?></td>
                            <td><?php echo $data['describe'];?></td>
                            <td><?php echo $data['userName'];?></td>
                            <td>
                              <?php if($data['status'] == 0):?>
                                <?php echo '待回复' ;?>
                              <?php elseif($data['status'] == 1):?>
                                <?php echo '成功' ;?>
                              <?php else:?>
                                <?php echo '失败' ;?>
                              <?php endif;?> 
                            </td>
                            <td>
                              <button class="btn btn-info btn-sm match" data-id="<?php echo $data['id'];?>">确定匹配</button>
                            </td>
                          </tr>
                        <?php endforeach;?>
                      <?php else:?>
                        <td colspan="5" style="text-align: center;">暂无信息</td>
                      <?php endif;?>
                    </tbody>
                  </table>
                  <?php if(!empty($pager['data'])):?>
                    {include file="../application/index/view/public/pager.phtml" /}
                  <?php endif;?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 匹配置换请求接口 start -->
    <div class="modal fade bs-example-modal-md" id="addMatchModal">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">配置置换请求</h4>
          </div>
          <div class="modal-body open-user-modal">
            <form class="form-horizontal form-label-left" id="addMatchForm">
              <input type="hidden" name="goodsId" id="goodsId" value="<?php echo $goods['id'] ;?>">
              <input type="hidden" name="requestId" id="requestId">
              <input type="hidden" name="userAddressee" id="userAddressee">
              <input type="hidden" name="addressMobile" id="addressMobile">
              <input type="hidden" name="userAddress" id="userAddress">
              <div class="form-group">
                <label class="control-label col-sm-3" for="addressList">收件地址</label>
                <div class="col-md-9 col-sm-9 col-xs-12">
                  <?php if(!empty($address)):?>
                    <?php foreach ($address as $key=>$data):?>
                      <div class="radio">
                        <label>
                          <input type="radio" value="<?php echo $data['addressee'].'-'.$data['mobile'].'-'.$data['address'] ;?>" name="addressList"><?php echo $data['addressee'];?> - <?php echo $data['mobile'];?> - <?php echo $data['address'];?>
                        </label>
                      </div>
                    <?php endforeach;?>
                  <?php else:?>
                    <a href="/user/index/addressList" class="btn btn-info btn-sm">前往设置地址</a>
                  <?php endif;?>
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="addMatch">确认匹配</button>
          </div>
        </div>
      </div>
    </div>
    <!-- 匹配置换请求接口 end -->

    <script>
      (() => {
        // 设置基本信息
        $('.match').click(function() {
          $('#requestId').val($(this).attr('data-id'));
          $('#addMatchModal').modal('show');
        });
        $('#addMatch').click(() => {
          if ($("input[type='radio']:checked").val()) {
            const address = $("input[type='radio']:checked").val().split('-');
            $('#userAddressee').val(address[0]);
            $('#addressMobile').val(address[1]);
            $('#userAddress').val(address[2]);
            const params = $('#addMatchForm').serializeArray();
            $.post('/user/order/add', params, (res) => {
              if (res.status === true) {
                location.reload();
              } else {
                alert(res.msg);
              }
            });
          } else {
            alert('请先选择地址');
          }
        });
      })();
    </script>
{include file="../application/index/view/public/footer.phtml" /}