{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/user-side.phtml" /}
    {include file="../application/index/view/public/user-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>发起匹配成功订单列表</h3>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>待置换用户</th>
                        <th>待置换商品</th>
                        <th>我的置换商品</th>
                        <th>状态</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if(!empty($pager['data'])):?>
                        <?php foreach ($pager['data'] as $key=>$data):?>
                          <tr role="row">
                            <td><?php echo $data['changer'];?></td>
                            <td><?php echo $data['changeGoodsName'];?></td>
                            <td><?php echo $data['goodsName'];?></td>
                            <td><?php echo $data['status'];?></td>
                            <td>
                              <?php if($data['status'] == '处理中'):?>
                                <button class="btn btn-info btn-sm cancel" data-id="<?php echo $data['id'];?>">取消匹配</button>
                              <?php endif;?>
                              <a href="/user/order/detail?id=<?php echo $data['id'];?>" class="btn btn-info btn-sm">匹配详情</a>
                            </td>
                          </tr>
                        <?php endforeach;?>
                      <?php else:?>
                        <td colspan="5" style="text-align: center;">暂无信息</td>
                      <?php endif;?>
                    </tbody>
                  </table>
                  <?php if(!empty($pager['data'])):?>
                    {include file="../application/index/view/public/pager.phtml" /}
                  <?php endif;?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
      // 取消匹配
      $('.cancel').click(function() {
        if (confirm('确定取消该匹配请求？')) {
          const params = {
            orderId: $(this).attr('data-id')
          }
          $.post('/user/order/cancel', params, (res) => {
            if (res.status === true) {
              location.reload();
            } else {
              alert(res.msg);
            }
          })
        }
      });
    </script>
{include file="../application/index/view/public/footer.phtml" /}