{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/user-side.phtml" /}
    {include file="../application/index/view/public/user-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>发起匹配成功订单列表</h3>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>待置换用户</th>
                        <th>待置换商品</th>
                        <th>我的置换商品</th>
                        <th>状态</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if(!empty($pager['data'])):?>
                        <?php foreach ($pager['data'] as $key=>$data):?>
                          <tr role="row">
                            <td><?php echo $data['changer'];?></td>
                            <td><?php echo $data['changeGoodsName'];?></td>
                            <td><?php echo $data['goodsName'];?></td>
                            <td><?php echo $data['status'];?></td>
                            <td>
                              <?php if($data['status'] == '处理中'):?>
                                <button class="btn btn-info btn-sm cancel" data-id="<?php echo $data['id'];?>">取消匹配</button>
                              <?php endif;?>
                              <a href="/user/order/detail?id=<?php echo $data['id'];?>" class="btn btn-info btn-sm">匹配详情</a>
                              <button class="btn btn-danger btn-sm showReportModal" data-id="<?php echo $data['id'];?>">举报</button>
                            </td>
                          </tr>
                        <?php endforeach;?>
                      <?php else:?>
                        <td colspan="5" style="text-align: center;">暂无信息</td>
                      <?php endif;?>
                    </tbody>
                  </table>
                  <?php if(!empty($pager['data'])):?>
                    {include file="../application/index/view/public/pager.phtml" /}
                  <?php endif;?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- 举报 start -->
    <div class="modal fade bs-example-modal-md" id="reportModal">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">举报</h4>
          </div>
          <div class="modal-body open-user-modal">
            <form class="form-horizontal form-label-left" id="reportForm">
              <input type="hidden" name="order_id" id="order_id">
              <div class="form-group">
                <label for="type" class="col-sm-3 control-label">举报类型</label>
                <div class="col-sm-3">
                  <select name="type" class="form-control">
                    <option value="0" selected="selected">普通</option>
                    <option value="1">交易举报</option>
                    <option value="2">信誉举报</option>
                  </select>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="reason">举报原因</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <textarea name="reason" type="text" class="form-control" placeholder="请输入举报原因"></textarea>
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="report">确定</button>
          </div>
        </div>
      </div>
    </div>
    <!-- 举报 end -->

    <script>
      // 取消匹配
      $('.cancel').click(function() {
        if (confirm('确定取消该匹配请求？')) {
          const params = {
            orderId: $(this).attr('data-id')
          }
          $.post('/user/order/cancel', params, (res) => {
            if (res.status === true) {
              location.reload();
            } else {
              alert(res.msg);
            }
          })
        }
      });

      // 举报
      $('.showReportModal').click(function() {
          $('#order_id').val($(this).attr('data-id'));
          $('#reportModal').modal('show');
        });
        $('#report').click(() => {
          const params = $('#reportForm').serializeArray();
          $.post('/user/order/report', params, (res) => {
            alert(res.msg);
            if (res.status === true) {
              location.reload();
            }
          });
        });
    </script>
{include file="../application/index/view/public/footer.phtml" /}