{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/user-side.phtml" /}
    {include file="../application/index/view/public/user-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>置换请求管理</h3>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>置换商品名称</th>
                        <th>意向商品名称</th>
                        <th>意向商品原价</th>
                        <th>意向商品描述</th>
                        <th>状态</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if(!empty($pager['data'])):?>
                        <?php foreach ($pager['data'] as $key=>$data):?>
                          <tr role="row">
                            <td><?php echo $data['change_goods_name'];?></td>
                            <td><?php echo $data['goods']['name'];?></td>
                            <td><?php echo $data['goods']['price'];?></td>
                            <td><?php echo $data['goods']['describe'];?></td>
                            <td>
                              <?php if($data['status'] == 0):?>
                                <?php echo '待回复' ;?>
                              <?php elseif($data['status'] == 1):?>
                                <?php echo '成功' ;?>
                              <?php else:?>
                                <?php echo '失败' ;?>
                              <?php endif;?> 
                            </td>
                            <td>
                              <a class="btn btn-info btn-sm look" href="<?php echo $data['goods']['photo'];?>" target="_blank">查看意向商品图片</a>
                              <button class="btn btn-danger btn-sm cancel" data-id="<?php echo $data['id'];?>">取消置换请求</button>
                            </td>
                          </tr>
                        <?php endforeach;?>
                      <?php else:?>
                        <td colspan="6" style="text-align: center;">暂无信息</td>
                      <?php endif;?>
                    </tbody>
                  </table>
                  <?php if(!empty($pager['data'])):?>
                    {include file="../application/index/view/public/pager.phtml" /}
                  <?php endif;?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      (() => (
        // 取消置换请求
        $('.cancel').click(function() {
          if (confirm('确定取消该置换请求？')) {
            const params = {
              id: $(this).attr('data-id')
            }
            $.post('/user/request/cancel', params, (res) => {
            if (res.status === true) {
                location.reload();
              } else {
                alert(res.msg);
              }
            });
          }
        })
      ))();
    </script>
{include file="../application/index/view/public/footer.phtml" /}