<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>交易管理系统</title>
    <!-- Bootstrap -->
    <link href="/assets/plugins/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/assets/plugins/nprogress/nprogress.css" rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="/assets/plugins/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="/assets/css/build/custom.min.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="/assets/plugins/animate.css/animate.min.css" rel="stylesheet">
    <!-- jQuery -->
    <script src="/assets/plugins/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/assets/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/lib/cookie.js"></script>
  </head>

  <body class="login">
    <div>
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form>
              <h1>用户注册</h1>
              <div>
                <input type="email" class="form-control" placeholder="邮箱" required="" id="email"/>
              </div>
              <div style="margin-bottom: 10px;">
                <input type="text" class="form-control" placeholder="验证码" id="code" style="width: 226px;display: inline-block;vertical-align: middle;margin: 0;">
                <a style="vertical-align: middle;display: inline-block;height: 34px;margin: 0;width: 120px;line-height: 34px;color: #42ade6;cursor: pointer;" id="sendCode">获取邮箱验证码</a>
              </div>
              <div>
                <input type="password" class="form-control" placeholder="密码" required="" id="password"/>
              </div>
              <div>
                <input type="password" class="form-control" placeholder="确认密码" required="" id="sure"/>
              </div>
              <div>
                <a class="btn btn-default submit" id="register">注册</a>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">已有帐号 ?
                  <a href="/user/login" class="to_register">前往登录</a>
                </p>
                <div class="clearfix"></div>
                <br />
              </div>
            </form>
          </section>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      showBtn = getCookie('email') === '' ? true : false;
      (function(){
        countTime('email', 'sendCode');
        // 注册
        $('#register').click(function() {
          var params = {
            email: $('#email').val(),
            password: $('#password').val(),
            sure: $('#sure').val(),
            code: $('#code').val()
          }
          //登陆
          $.get('/user/regist/i', params, function(data){
            if (data.status === true) {
              window.location.href = '/';
            } else {
              alert(data.msg);
            }
          })
        })
        // 获取邮箱验证码
        $('#sendCode').click(function() {
          if (showBtn) {
            $.post('/index/email/regist', {email: $('#email').val()}, function(res) {
              if (res.status == true) {
                setCookie('email', 60, 60 * 1000)
                  showBtn = false
                  countTime('email', 'sendCode')
              } else {
                alert(res.msg);
              }
            })
          }
        });

        document.onkeydown = function(e){    
          var e = window.event ? window.event:e;
          if(e.keyCode == 13){
            $('#login').click()
         }
        }
      })();

      // 验证码获取倒计时
      function countTime (name, idName) {
        if (getCookie(name) === '') {
          $('#' + idName).text('获取邮箱验证码');
          showBtn = true;
          return false;
        } else {
          var sec = parseInt(getCookie(name));

          setTimeout(function() {
              sec--;
              $('#' + idName).text('已发送(' + sec + ')');
              setCookie(name, sec, sec * 1000);

              countTime(name, idName);
          }, 1000)
        }
      }
    </script>
    <script src="/assets/plugins/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/assets/plugins/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="/assets/plugins/Chart.js/dist/Chart.min.js"></script>
    <!-- jQuery Sparklines -->
    <script src="/assets/plugins/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
    <!-- Flot -->
    <script src="/assets/plugins/Flot/jquery.flot.js"></script>
    <script src="/assets/plugins/Flot/jquery.flot.pie.js"></script>
    <script src="/assets/plugins/Flot/jquery.flot.time.js"></script>
    <script src="/assets/plugins/Flot/jquery.flot.stack.js"></script>
    <script src="/assets/plugins/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="/assets/plugins/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="/assets/plugins/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="/assets/plugins/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="/assets/plugins/DateJS/build/date.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="/assets/plugins/moment/min/moment.min.js"></script>
    <script src="/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
    
    <!-- Custom Theme Scripts -->
    <script src="/assets/plugins/build/custom.min.js"></script>
  </body>
</html>