{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/admin-side.phtml" /}
    {include file="../application/index/view/public/admin-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>公告列表</h3>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-10 col-md-10">
                  <button class="btn btn-primary btn-sm" id="showAddMsgModal">添加公告</button>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>标题</th>
                        <th>内容</th>
                        <th>权重</th>
                        <th>发布</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if(!empty($pager['data'])):?>
                        <?php foreach ($pager['data'] as $key=>$data):?>
                          <tr role="row">
                            <td><?php echo $data['title'];?></td>
                            <td><?php echo $data['content'];?></td>
                            <td><?php echo $data['weight'];?></td>
                            <td>
                              <?php if($data['is_issue'] == 0):?>
                                <?php echo '待发布' ;?>
                              <?php elseif($data['is_issue'] == 1):?>
                                <?php echo '已发布' ;?>
                              <?php endif;?> 
                            </td>
                            <td>
                              <button class="btn btn-info btn-sm edit" data-id="<?php echo $data['id'];?>" data-info="<?php echo implode(',', $data);?>">修改</button>
                              <button class="btn btn-danger btn-sm cancel" data-id="<?php echo $data['id'];?>">删除</button>
                            </td>
                          </tr>
                        <?php endforeach;?>
                      <?php else:?>
                        <td colspan="5" style="text-align: center;">暂无信息</td>
                      <?php endif;?>
                    </tbody>
                  </table>
                  <?php if(!empty($pager['data'])):?>
                    {include file="../application/index/view/public/pager.phtml" /}
                  <?php endif;?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade bs-example-modal-md" id="addMsgModal">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">添加公告</h4>
          </div>
          <div class="modal-body open-user-modal">
            <form class="form-horizontal form-label-left" id="addMsgForm">
              <div class="form-group">
                <label class="control-label col-sm-3" for="title">公告标题</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="title" type="text" class="form-control" placeholder="请输入公告标题">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="content">公告内容</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <textarea name="content" class="form-control" placeholder="请输入公告内容"></textarea>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="weight">权重</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="weight" type="number" class="form-control" placeholder="请输入权重">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="is_issue">发布</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <label class="radio-inline">
                    <input type="radio" name="is_issue" value="0" checked>否
                  </label>

                  <label class="radio-inline">
                     <input type="radio" name="is_issue" value="1">是
                  </label>
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="addMsg">添加</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade bs-example-modal-md" id="editMsgModal">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">修改公告</h4>
          </div>
          <div class="modal-body open-user-modal">
            <form class="form-horizontal form-label-left" id="editMsgForm">
              <div class="form-group">
                <input name="id" type="hidden" id="id"> 
                <label class="control-label col-sm-3" for="title">公告标题</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="title" type="text" class="form-control" placeholder="请输入公告标题" id="title">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="content">公告内容</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <textarea name="content" class="form-control" placeholder="请输入公告内容" id="content"></textarea>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="weight">权重</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <input name="weight" type="number" class="form-control" placeholder="请输入权重" id="weight">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-3" for="is_issue">发布</label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <label class="radio-inline">
                    <input type="radio" name="is_issue" value="0" checked>否
                  </label>
                  <label class="radio-inline">
                     <input type="radio" name="is_issue" value="1">是
                  </label>
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="editMsg">确定</button>
          </div>
        </div>
      </div>
    </div>

    <script>
      (() => {
        // 添加公告
        $('#showAddMsgModal').click(() => {
          $('#addMsgModal').modal('show');
        });
        $('#addMsg').click(() => {
          const params = $('#addMsgForm').serializeArray();
          $.post('/admin/msg/add', params, (res) => {
            if (res.status === true) {
              location.reload();
            } else {
              alert(res.msg);
            }
          })
        });
        // 修改公告
        $('.edit').click(function() {
          const arr = $(this).attr('data-info').split(',');
          $('#id').val(arr[0]);
          $('#title').val(arr[1]);
          $('#content').val(arr[2]);
          $('#weight').val(arr[4]);
          $('#editMsgModal').modal('show');
        });
        $('#editMsg').click(() => {
          const params = $('#editMsgForm').serializeArray();
          $.post('/admin/msg/update', params, (res) => {
            if (res.status === true) {
              location.reload();
            } else {
              alert(res.msg);
            }
          })
        });
        // 删除公告
        $('.cancel').click(function() {
          if (confirm('确定删除改公告？')) {
            const params = {
              id: $(this).attr('data-id')
            }
            $.post('/admin/msg/delete', params, (res) => {
            if (res.status === true) {
                location.reload();
              } else {
                alert(res.msg);
              }
            });
          }
        })
      })();
    </script>
{include file="../application/index/view/public/footer.phtml" /}