<div class="container body">
  <div class="main_container">

    <!-- 左侧边栏 start -->
    <div class="col-md-3 left_col">
      <!-- 左侧边栏上班部分 start -->
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;text-align: center;">
          <a href="#" class="site_title" style="padding: 0; font-size: 22px;"><i class="fa fa-paw"></i> <span>用品置换交易</span></a>
        </div>

        <div class="clearfix"></div>

        <br />
        <!-- 左侧边栏上班部分 end-->
        
        <!-- 索引sidebar start -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div class="menu_section">
            <h3>功能列表</h3>
            <ul class="nav side-menu">
              <li>
                <a href="/user/index"><i class="fa fa-home"></i>个人中心<span class="fa"></span></a>
              </li>
              <li>
                <a href="/index/index/index"><i class="fa fa-home"></i>置换商城<span class="fa"></span></a>
              </li>
              <li>
                <a href="/user/goods/index"><i class="fa fa-cog"></i>置换商品管理<span class="fa"></span></a>
              </li>
              <li>
                <a href="/user/request/index"><i class="fa fa-cog"></i>置换请求管理<span class="fa"></span></a>
              </li>
              <li>
                <a><i class="fa fa-cog"></i>订单管理<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="/user/order/index">发起匹配成功订单列表</a></li>
                  <li><a href="/user/order/pipei">请求匹配成功订单列表</a></li>
                </ul>
              </li>
              <!-- <li>
                <a href="/admin/manage/userlist"><i class="fa fa-user"></i>用户列表<span class="fa"></span></a>
              </li> -->
            </ul>
          </div>
        </div>
        <!-- 索引sidebar end -->
      </div>
    </div>