    <div class="container body">
      <div class="main_container">

        <!-- 左侧边栏 start -->
        <div class="col-md-3 left_col">
          <!-- 左侧边栏上班部分 start -->
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;text-align: center;">
              <a href="#" class="site_title" style="padding: 0; font-size: 22px;"><i class="fa fa-paw"></i> <span>交易后台</span></a>
            </div>

            <div class="clearfix"></div>

            <br />
            <!-- 左侧边栏上班部分 end-->
            
            <!-- 索引sidebar start -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>功能列表</h3>
                <ul class="nav side-menu">
                  <li>
                    <a href="/user/index"><i class="fa fa-home"></i> 首页 <span class="fa"></span></a>
                  </li>
                  <li>
                    <a><i class="fa fa-home"></i> 功能 <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#">功能2</a></li>
                      <li><a href="#">功能1</a></li>
                    </ul>
                  </li>
                  <li>
                    <a href="#"><i class="fa fa-home"></i> 开发文档 <span class="fa"></span></a>
                  </li>
                </ul>
              </div>
            </div>
            <!-- 索引sidebar end -->
          </div>
        </div>