{include file="../application/index/view/public/header.phtml" /}
  {include file="../application/index/view/public/user-side.phtml" /}
    {include file="../application/index/view/public/user-nav.phtml" /}
    <div class="right_col" role="main">
      <div class="">
        <div class="row x_title">
          <div class="col-md-12">
            <h3>地址管理</h3>
          </div>
        </div>

        <div class="x_content">
          <div class="text-muted font-13 m-b-30">
            <div class="dataTables_wrapper dt-bootstrap no-footer">
              <div class="row">
                <div class="col-sm-10 col-md-10">
                  <button class="btn btn-primary btn-sm" id="showAddAddressModal">添加地址</button>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <table id="datatable" class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>收件人</th>
                        <th>手机号</th>
                        <th>地址</th>
                        <th>是否为默认地址</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php if(!empty($address)):?>
                        <?php foreach ($address as $key=>$data):?>
                          <tr role="row">
                            <td><?php echo $data['addressee'];?></td>
                            <td><?php echo $data['mobile'];?></td>
                            <td><?php echo $data['address'];?></td>
                            <td><?php echo $data['is_default'] == '0' ? '是' : '否';?></td>
                            <td>
                              <button class="btn btn-info btn-sm edit" data-id="<?php echo $data['id'];?>" data-info="<?php echo implode(',', $data);?>">修改</button>
                              <button class="btn btn-danger btn-sm delete" data-id="<?php echo $data['id'];?>">删除</button>
                            </td>
                          </tr>
                        <?php endforeach;?>
                      <?php else:?>
                        <td colspan="5" style="text-align: center;">暂无信息</td>
                      <?php endif;?>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade bs-example-modal-md" id="addAddressModal">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">添加地址</h4>
          </div>
          <div class="modal-body open-user-modal">
            <form class="form-horizontal form-label-left" id="addAddressForm">
              <div class="form-group">
                  <label class="control-label col-sm-3" for="addressee">收件人</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input name="addressee" type="text" class="form-control" placeholder="请输入收件人">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-sm-3" for="mobile">手机号</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input name="mobile" type="number" class="form-control" placeholder="请输入手机号">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-sm-3" for="address">地址</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input name="address" type="text" class="form-control" placeholder="请输入地址">
                  </div>
                </div>
                <div class="form-group">
                  <label for="isDefault" class="col-sm-3 control-label">设为默认地址</label>
                  <div class="col-sm-9">
                      <label class="radio-inline">
                        <input type="radio" name="isDefault" value="0" checked>是
                      </label>
                      <label class="radio-inline">
                        <input type="radio" name="isDefault" value="1">否
                      </label>
                  </div>
                </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="addAddress">添加</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade bs-example-modal-md" id="editAddressModal">
      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">修改地址</h4>
          </div>
          <div class="modal-body open-user-modal">
            <form class="form-horizontal form-label-left" id="editAddressForm">
              <input name="id" type="hidden" class="form-control" id="id">
              <div class="form-group">
                  <label class="control-label col-sm-3" for="addressee">收件人</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input name="addressee" type="text" class="form-control" placeholder="请输入收件人" id="addressee">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-sm-3" for="mobile">手机号</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input name="mobile" type="number" class="form-control" placeholder="请输入手机号" id="mobile">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-sm-3" for="address">地址</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input name="address" type="text" class="form-control" placeholder="请输入地址" id="address">
                  </div>
                </div>
                <div class="form-group">
                  <label for="isDefault" class="col-sm-3 control-label">设为默认地址</label>
                  <div class="col-sm-9">
                    <label class="radio-inline">
                      <input type="radio" name="isDefault" value="0" id="radio0">是
                    </label>
                    <label class="radio-inline">
                      <input type="radio" name="isDefault" value="1" id="radio1">否
                    </label>
                  </div>
                </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="editAddress">修改</button>
          </div>
        </div>
      </div>
    </div>

    <script>
      (() => {
        // 添加地址
        $('#showAddAddressModal').click(() => {
          $('#addAddressModal').modal('show');
        });
        $('#addAddress').click(() => {
          const params = $('#addAddressForm').serializeArray();
          $.post('/user/index/addAddress', params, (res) => {
            if (res.status === true) {
              location.reload();
            } else {
              alert(res.msg);
            }
          })
        });
        // 修改地址
        $('.edit').click(function() {
          const arr = $(this).attr('data-info').split(',');
          $('#id').val(arr[0]);
          $('#addressee').val(arr[5]);
          $('#mobile').val(arr[6]);
          $('#address').val(arr[1]);
          $('#radio' + arr[3]).attr("checked","checked");
          $('#editAddressModal').modal('show');
        });
        $('#editAddress').click(() => {
          const params = $('#editAddressForm').serializeArray();
          $.post('/user/index/updateAddress', params, (res) => {
            if (res.status === true) {
              location.reload();
            } else {
              alert(res.msg);
            }
          })
        });
        // 删除地址
        $('.delete').click(function() {
          if (confirm('确定删除该地址？')) {
            const params = {
              id: $(this).attr('data-id')
            }
            $.post('/user/index/delAddress', params, (res) => {
              if (res.status === true) {
                location.reload();
              } else {
                alert(res.msg);
              }
            })
          }
        });
      })();
    </script>
{include file="../application/index/view/public/footer.phtml" /}